#!/usr/bin/env python3
"""Regenerate the pin manifest lerd reads, from every pin on record.

    scripts/manifest.py <pinsdir> <out.yaml>

Each build drops a pin describing the asset it produced, and those are kept in
pins/ so a run that rebuilds one minor does not drop the other four out of the
manifest. The download URL is derived from the patch, because a release is
tagged for the PHP it carries.
"""
import json, pathlib, sys

pinsdir, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])

pins = {}
for f in sorted(pinsdir.glob("*.json")):
    p = json.loads(f.read_text())
    pins.setdefault(p["minor"], []).append(p)

if not pins:
    sys.exit("manifest.py: no pins in %s" % pinsdir)

lines = ["# Generated by lerd-env/php. Do not edit: scripts/manifest.py rewrites",
         "# this from pins/ every time a build publishes.",
         "tools:"]
for minor in sorted(pins, key=lambda m: [int(n) for n in m.split(".")]):
    entries = sorted(pins[minor], key=lambda p: p["platform"])
    versions = {p["version"] for p in entries}
    # Two architectures of one minor must be the same patch, or which PHP a
    # machine gets would depend on which architecture it happens to be.
    if len(versions) != 1:
        sys.exit("manifest.py: %s pinned at %s across platforms" % (minor, ", ".join(sorted(versions))))
    patch = entries[0]["version"]
    lines.append("  php-native-%s:" % minor)
    lines.append('    version: "%s"' % patch)
    lines.append("    url: https://github.com/lerd-env/php/releases/download/php-%s/{asset}" % patch)
    for field, key in (("assets", "asset"), ("digests", "sha256"), ("sizes", "size")):
        lines.append("    %s:" % field)
        for p in entries:
            lines.append("      %s: %s" % (p["platform"], p[key]))

out.write_text("\n".join(lines) + "\n")
print("\n".join(lines))
