#!/usr/bin/env python3
"""Regenerate the pin manifest lerd reads, from every pin on record.

    scripts/manifest.py <pinsdir> <out.yaml>

Each build drops a pin describing the asset it produced, and those are kept in
pins/ so a run that rebuilds one minor does not drop the other four out of the
manifest. The download URL is derived from the patch, because a release is
tagged for the PHP it carries.
"""
import json, pathlib, sys

# The one platform allowed to trail the others; see below.
WINDOWS = "windows/amd64"

pinsdir, out =pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])

pins = {}
for f in sorted(pinsdir.glob("*.json")):
    p = json.loads(f.read_text())
    pins.setdefault(p["minor"], []).append(p)

if not pins:
    sys.exit("manifest.py: no pins in %s" % pinsdir)

lines = ["# Generated by lerd-env/php. Do not edit: scripts/manifest.py rewrites",
         "# this from pins/ every time a build publishes.",
         "tools:"]
for minor in sorted(pins, key=lambda m: [int(n) for n in m.split(".")]):
    entries = sorted(pins[minor], key=lambda p: p["platform"])
    # Every platform of one minor must be the same patch, or which PHP a machine
    # gets would depend on what it runs. The macOS builds come from the same
    # source in the same run, so a mismatch between them means a run built one
    # architecture on a new patch, and that stops the manifest.
    leading = [p for p in entries if p["platform"] != WINDOWS] or entries
    versions = {p["version"] for p in leading}
    if len(versions) != 1:
        sys.exit("manifest.py: %s pinned at %s across platforms" % (minor, ", ".join(sorted(versions))))
    patch = leading[0]["version"]
    # windows.php.net publishes its build hours after php.net announces a patch,
    # so Windows alone may trail macOS by a run. It drops out of the manifest
    # until it catches up, rather than holding macOS on the old patch. Ahead of
    # macOS it is a missing macOS build, and that stops the manifest too.
    for p in entries:
        if p["version"] == patch:
            continue
        if [int(n) for n in p["version"].split(".")] > [int(n) for n in patch.split(".")]:
            sys.exit("manifest.py: %s %s is on %s, ahead of macOS on %s"
                     % (minor, p["platform"], p["version"], patch))
        print("manifest.py: %s %s is still on %s, leaving it out until it reaches %s"
              % (minor, p["platform"], p["version"], patch), file=sys.stderr)
    entries = [p for p in entries if p["version"] == patch]
    lines.append("  php-native-%s:" % minor)
    lines.append('    version: "%s"' % patch)
    lines.append("    url: https://github.com/lerd-env/php/releases/download/php-%s/{asset}" % patch)
    # A rebuild of an already published patch carries the same version as the
    # build it replaces, so the version alone cannot tell lerd it is looking at
    # a different one. Per platform like the digest beside it: a run that builds
    # one architecture leaves the other's date alone, and the machines on it
    # have no reason to fetch the asset they already hold.
    if any(p.get("published") for p in entries):
        lines.append("    published:")
        for p in entries:
            if p.get("published"):
                lines.append('      %s: "%s"' % (p["platform"], p["published"]))
    for field, key in (("assets", "asset"), ("digests", "sha256"), ("sizes", "size")):
        lines.append("    %s:" % field)
        for p in entries:
            lines.append("      %s: %s" % (p["platform"], p[key]))

out.write_text("\n".join(lines) + "\n")
print("\n".join(lines))
